root: true
env:
  node: true
  browser: true
  es2020: true
extends:
  - next/core-web-vitals
  - eslint:recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended
  - plugin:jsx-a11y/recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:import/errors
  - plugin:import/warnings
  - prettier
  - plugin:storybook/recommended
plugins:
  - "@typescript-eslint"
  - react-hooks
  - jsx-a11y
  - import
  - unused-imports
settings:
  react:
    version: detect
  import/resolver:
    typescript:
      config: tsconfig.json
      alwaysTryTypes: true
overrides:
  - files: ["*.ts", "*.tsx"]
    parser: "@typescript-eslint/parser"
    parserOptions:
      project: tsconfig.json
      ecmaFeatures:
        jsx: true
      ecmaVersion: 2020
      sourceType: module
    rules:
      no-unused-vars: off
      "@typescript-eslint/no-unused-vars":
        - error
        - vars: "all"
          args: "after-used"
          ignoreRestSiblings: false
          argsIgnorePattern: "^_"
      react/prop-types: "off"
      jsx-a11y/anchor-is-valid: "off"
      import/default: "off"
      import/no-named-as-default-member: "off"
      import/order:
        - error
        - groups:
            [
              "builtin",
              "external",
              "internal",
              "index",
              "object",
              "parent",
              "sibling",
            ]
          newlines-between: always
          alphabetize:
            order: asc
      unused-imports/no-unused-imports: "error"
      react-hooks/exhaustive-deps: "error"
  - files: "*.stories.tsx"
    rules:
      no-console: "off"
